name: Automated Pipeline

on: push

jobs:
  pipline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependecies
        run: |
          npm cache clean --force
          cd battery-ui
          npm install
          cd .. 
          cd streaming-service
          npm install
          cd ..
          cd data-emulator
          npm install
          cd ..
          npm install

      - name: Testing
        run:  npm test