name: Automated Pipeline

on: push

jobs:
  pipline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.0 

      - name: Install dependecies
        run: |
          cd battery-ui
          rm node_modules
          npm install
          cd .. 
          cd streaming-service
          rm node_modules
          npm install
          npm update
          cd ..
          cd data-emulator
          rm node_modules
          npm install
          npm update
          cd ..
          rm node_modules
          npm install
          npm update

      - name: Testing
        run:  npm test