name: Automated Pipeline

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependecies
        run: npm install

      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        run: npm run lint