name: Automated Pipline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  linting:
    runs-on: ubuntu-latest

  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: linting
      run: npm run lint 